lang: en
title: openSUSE Debug Info
title_short: Debug Info
description: Information about using debuginfod with openSUSE distributions
email: admin@opensuse.org
copyright: '© 2020 openSUSE contributors'
baseurl: ""
url: "https://debuginfod.opensuse.org"
github_url: "https://github.com/openSUSE/debuginfod-o-o"

navbar_links:
  -
    link: https://software.opensuse.org/distributions/tumbleweed
    text: What is Tumbleweed?
  -
    link: https://download.opensuse.org/
    text: Repositories

footer_links:
  -
    text: Source Code
    link: https://github.com/openSUSE/debuginfod-o-o
  -
    text: License
    link: https://github.com/openSUSE/debuginfod-o-o/blob/master/COPYING

# Only edit below if you know what you are doing!

defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "markdown"
  -
    scope:
      path: "*.markdown"
    values:
      layout: "markdown"

disable_search: true

theme: jekyll-theme-opensuse
markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
